export const foods = [
  { name: "Nasi Padang", category: ["Nasi"] },
  { name: "Nasi Campur", category: ["Nasi"] },
  { name: "Nasi Goreng", category: ["Nasi", "Chinese", "Kaki Lima"] },
  { name: "Nasi Uduk", category: ["Nasi"] },
  { name: "Nasi Lemak", category: ["Nasi"] },
  { name: "Nasi Bakar", category: ["Nasi"] },
  { name: "Nasi Gila", category: ["Nasi"] },
  { name: "Nasi Liwet", category: ["Nasi"] },
  { name: "Nasi Pecel", category: ["Nasi"] },
  { name: "Nasi Lalapan", category: ["Nasi"] },
  { name: "Nasi Kuning", category: ["Nasi"] },
  {
    name: "Nasi Kebuli",
    category: ["Nasi", "Daging Kambing", "Timur Tengah"],
  },
  {
    name: "Nasi Biryani",
    category: ["Nasi", "Daging Kambing", "Timur Tengah"],
  },
  { name: "Nasi Hainan", category: ["Nasi", "Daging Ayam"] },
  { name: "Bakso", category: ["Makanan Berkuah", "Daging Sapi", "Kaki Lima"] },
  { name: "Rawon", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Sop Ayam", category: ["Makanan Berkuah", "Daging Ayam"] },
  { name: "Sop Iga", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Sop Buntut", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Konro", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Soto Lamongan", category: ["Makanan Berkuah", "Kaki Lima"] },
  { name: "Soto Betawi", category: ["Makanan Berkuah"] },
  { name: "Soto Banjar", category: ["Makanan Berkuah"] },
  { name: "Coto Makassar", category: ["Makanan Berkuah", "Daging Sapi"] },
  {
    name: "Gulai",
    category: ["Makanan Berkuah", "Daging Sapi", "Daging Kambing", "Kaki Lima"],
  },
  {
    name: "Tongseng",
    category: ["Makanan Berkuah", "Daging Sapi", "Daging Kambing"],
  },
  { name: "Ramen", category: ["Makanan Berkuah", "Jepang"] },
  { name: "Pho", category: ["Makanan Berkuah"] },
  { name: "Tom Yum", category: ["Makanan Berkuah"] },
  { name: "Hot Pot", category: ["Makanan Berkuah", "Chinese"] },
  { name: "Bakmie", category: ["Mie"] },
  { name: "Mie Ayam", category: ["Mie", "Daging Ayam", "Kaki Lima"] },
  { name: "Mie Yamin", category: ["Mie"] },
  { name: "Mie Goreng", category: ["Mie", "Chinese", "Kaki Lima"] },
  { name: "Mie Aceh", category: ["Mie"] },
  { name: "Mie Tek-Tek", category: ["Mie", "Kaki Lima"] },
  { name: "Mie Godog", category: ["Mie", "Kaki Lima"] },
  { name: "Mie Kari", category: ["Mie"] },
  { name: "Cwi Mie", category: ["Mie", "Kaki Lima"] },
  { name: "Mie Laksa", category: ["Mie"] },
  { name: "Udon", category: ["Mie", "Jepang"] },
  { name: "Ramyeon", category: ["Mie", "Korea"] },
  { name: "Jajangmyeon", category: ["Mie", "Korea"] },
  { name: "Sushi", category: ["Seafood", "Nasi", "Jepang"] },
  { name: "Ikan Bakar", category: ["Seafood"] },
  { name: "Ikan Goreng", category: ["Seafood"] },
  { name: "Sop Ikan", category: ["Seafood", "Makanan Berkuah"] },
  { name: "Udang Goreng", category: ["Seafood"] },
  { name: "Udang Bakar", category: ["Seafood"] },
  { name: "Udang Asam Manis", category: ["Seafood"] },
  { name: "Udang Mentega", category: ["Seafood"] },
  { name: "Cumi Goreng Tepung", category: ["Seafood"] },
  { name: "Cumi Hitam", category: ["Seafood"] },
  { name: "Kerang Saus Padang", category: ["Seafood"] },
  { name: "Pepes Ikan", category: ["Seafood"] },
  { name: "Sate Ayam", category: ["Daging Ayam", "Kaki Lima"] },
  { name: "Sate Taichan", category: ["Daging Ayam"] },
  { name: "Ayam Goreng", category: ["Daging Ayam"] },
  { name: "Ayam Bakar", category: ["Daging Ayam"] },
  { name: "Ayam Panggang", category: ["Daging Ayam"] },
  { name: "Ayam Geprek", category: ["Daging Ayam"] },
  { name: "Ayam Kremes", category: ["Daging Ayam"] },
  { name: "Ayam Penyet", category: ["Daging Ayam"] },
  { name: "Ayam Rica-Rica", category: ["Daging Ayam"] },
  { name: "Ayam Betutu", category: ["Daging Ayam"] },
  { name: "Bubur Ayam", category: ["Daging Ayam", "Kaki Lima"] },
  { name: "Chicken Katsu", category: ["Daging Ayam", "Jepang"] },
  { name: "Chicken Wings", category: ["Daging Ayam"] },
  { name: "Yakitori", category: ["Daging Ayam"] },
  { name: "Bebek Goreng", category: ["Daging Bebek"] },
  { name: "Bebek Bakar", category: ["Daging Bebek"] },
  { name: "Bebek Panggang", category: ["Daging Bebek"] },
  { name: "Bebek Kremes", category: ["Daging Bebek"] },
  { name: "Bebek Hitam Madura", category: ["Daging Bebek"] },
  { name: "Sei Sapi", category: ["Daging Sapi"] },
  { name: "Soto Daging", category: ["Daging Sapi", "Makanan Berkuah"] },
  { name: "Tengkleng", category: ["Daging Sapi", "Daging Kambing"] },
  { name: "Sate Padang", category: ["Daging Sapi", "Kaki Lima"] },
  { name: "Steak", category: ["Daging Sapi", "Barat"] },
  { name: "Beef Bulgogi", category: ["Daging Sapi", "Korea"] },
  { name: "Beef Teriyaki", category: ["Daging Sapi", "Jepang"] },
  { name: "Sate Kambing", category: ["Daging Kambing", "Kaki Lima"] },
  { name: "Nasi Goreng Kambing", category: ["Daging Kambing", "Nasi"] },
  { name: "Burger", category: ["Fast Food", "Daging Sapi", "Barat"] },
  { name: "Pizza", category: ["Fast Food", "Barat"] },
  { name: "Fried Chicken", category: ["Fast Food", "Daging Ayam", "Barat"] },
  { name: "Sandwich", category: ["Fast Food", "Barat"] },
  { name: "Taco", category: ["Fast Food", "Barat"] },
  { name: "Bento", category: ["Fast Food", "Nasi", "Jepang"] },
  { name: "Kebab", category: ["Fast Food", "Timur Tengah"] },
  { name: "Sei Babi", category: ["Daging Babi"] },
  { name: "Babi Kecap", category: ["Daging Babi"] },
  { name: "Babi Rica-Rica", category: ["Daging Babi"] },
  { name: "Sate Babi", category: ["Daging Babi"] },
  { name: "Babi Goreng", category: ["Daging Babi"] },
  { name: "Kwetiau", category: ["Mie"] },
  { name: "Chicken Karaage", category: ["Daging Ayam", "Jepang"] },
  { name: "Yakiniku", category: ["Daging Sapi", "Jepang"] },
  {
    name: "Shabu-Shabu",
    category: ["Makanan Berkuah", "Daging Sapi", "Jepang"],
  },
  { name: "Sukiyaki", category: ["Makanan Berkuah", "Daging Sapi", "Jepang"] },
  { name: "Donburi", category: ["Nasi", "Jepang"] },
  { name: "Gyudon", category: ["Nasi", "Daging Sapi", "Jepang"] },
  { name: "Kimchi Jjigae", category: ["Makanan Berkuah", "Korea", "Sayuran"] },
  { name: "Bibimbap", category: ["Nasi", "Korea", "Sayuran"] },
  { name: "Kimbap", category: ["Nasi", "Korea"] },
  { name: "Sundubu Jjigae", category: ["Makanan Berkuah", "Korea", "Sayuran"] },
  { name: "Fuyunghai", category: ["Chinese"] },
  { name: "Bebek Peking", category: ["Daging Bebek", "Chinese"] },
  { name: "Sapo Tahu", category: ["Chinese"] },
  { name: "Koloke", category: ["Chinese"] },
  { name: "Cap Cai", category: ["Chinese", "Sayuran"] },
  { name: "Mapo Tahu", category: ["Chinese"] },
  { name: "Ayam Kungpao", category: ["Daging Ayam", "Chinese"] },
  { name: "Shawarma", category: ["Timur Tengah", "Fast Food"] },
  { name: "Nasi Mandhi", category: ["Nasi", "Timur Tengah"] },
  { name: "Roti Maryam", category: ["Timur Tengah", "Makanan Ringan"] },
  { name: "Sambosa", category: ["Timur Tengah", "Makanan Ringan"] },
  { name: "Baklava", category: ["Timur Tengah", "Makanan Ringan"] },
  { name: "Batagor", category: ["Makanan Ringan", "Kaki Lima"] },
  { name: "Seblak", category: ["Makanan Ringan", "Kaki Lima"] },
  { name: "Siomay", category: ["Makanan Ringan", "Kaki Lima"] },
  { name: "Dimsum", category: ["Chinese", "Makanan Ringan"] },
  { name: "Okonomiyaki", category: ["Jepang", "Makanan Ringan"] },
  { name: "Takoyaki", category: ["Jepang", "Makanan Ringan"] },
  { name: "Onigiri", category: ["Nasi", "Jepang", "Makanan Ringan"] },
  { name: "Gyoza", category: ["Jepang", "Makanan Ringan"] },
  { name: "Mochi", category: ["Jepang", "Makanan Ringan"] },
  { name: "Taiyaki", category: ["Jepang", "Makanan Ringan"] },
  { name: "Tempura", category: ["Jepang"] },
  { name: "Tteokbokki", category: ["Korea", "Makanan Ringan"] },
  { name: "Odeng", category: ["Korea", "Makanan Ringan"] },
  { name: "Hotteok", category: ["Korea", "Makanan Ringan"] },
  { name: "Bingsoo", category: ["Korea", "Makanan Ringan"] },
  { name: "Martabak", category: ["Makanan Ringan", "Kaki Lima"] },
  { name: "Terang Bulan", category: ["Makanan Ringan", "Kaki Lima"] },
  { name: "Chicken Cordon Bleu", category: ["Daging Ayam", "Barat"] },
  { name: "Fish & Chips", category: ["Seafood", "Barat"] },
  { name: "Pasta", category: ["Mie", "Barat"] },
  { name: "Lasagna", category: ["Barat"] },
  { name: "Mac & Cheese", category: ["Barat", "Fast Food"] },
  { name: "Croissant", category: ["Barat", "Makanan Ringan"] },
  { name: "Salad", category: ["Sayuran"] },
  { name: "Gado-Gado", category: ["Sayuran"] },
  { name: "Karedok", category: ["Sayuran"] },
  { name: "Sayur Asem", category: ["Sayuran"] },
  { name: "Sayur Lodeh", category: ["Sayuran"] },
  { name: "Sayur Bening", category: ["Sayuran"] },
  { name: "Pempek", category: ["Makanan Ringan"] },
  { name: "Tahu Telor", category: ["Kaki Lima"] },
  { name: "Ketoprak", category: ["Kaki Lima"] },
  { name: "Roti Bakar", category: ["Makanan Ringan", "Kaki Lima"] },
];

foods.sort((a, b) => a.name.localeCompare(b.name));

// export const foodCategories = [
//   ...new Set(foods.flatMap((food) => food.category)),
// ];

// foodCategories.sort();

export const foodCategories = [
  "Nasi",
  "Mie",
  "Makanan Berkuah",
  "Seafood",
  "Daging Ayam",
  "Daging Bebek",
  "Daging Sapi",
  "Daging Kambing",
  "Daging Babi",
  "Sayuran",
  "Fast Food",
  "Kaki Lima",
  "Barat",
  "Chinese",
  "Jepang",
  "Korea",
  "Timur Tengah",
  "Makanan Ringan",
];
