export const foods = [
  { name: "Nasi Padang", category: ["Aneka Nasi"] },
  { name: "Nasi Campur", category: ["Aneka Nasi"] },
  { name: "Nasi Goreng", category: ["Aneka Nasi"] },
  { name: "Nasi Uduk", category: ["Aneka Nasi"] },
  { name: "Nasi Lemak", category: ["Aneka Nasi"] },
  { name: "Nasi Bakar", category: ["Aneka Nasi"] },
  { name: "Nasi Gila", category: ["Aneka Nasi"] },
  { name: "Nasi Liwet", category: ["Aneka Nasi"] },
  { name: "Nasi Lalapan", category: ["Aneka Nasi"] },
  { name: "Nasi Kuning", category: ["Aneka Nasi"] },
  { name: "Nasi Kebuli", category: ["Aneka Nasi"] },
  { name: "Nasi Briyani", category: ["Aneka Nasi"] },
  { name: "Nasi Hainan", category: ["Aneka Nasi"] },
  { name: "Bakso", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Rawon", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Sop Ayam", category: ["Makanan Berkuah", "Daging Ayam"] },
  { name: "Sop Iga", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Sop Buntut", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Konro", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Soto Lamongan", category: ["Makanan Berkuah"] },
  { name: "Soto Betawi", category: ["Makanan Berkuah"] },
  { name: "Soto Banjar", category: ["Makanan Berkuah"] },
  { name: "Coto Makassar", category: ["Makanan Berkuah", "Daging Sapi"] },
  {
    name: "Gulai",
    category: ["Makanan Berkuah", "Daging Sapi", "Daging Kambing"],
  },
  {
    name: "Tongseng",
    category: ["Makanan Berkuah", "Daging Sapi", "Daging Kambing"],
  },
  { name: "Ramen", category: ["Makanan Berkuah"] },
  { name: "Pho", category: ["Makanan Berkuah"] },
  { name: "Tom Yum", category: ["Makanan Berkuah"] },
  { name: "Bakmie", category: ["Mie"] },
  { name: "Mie Ayam", category: ["Mie", "Daging Ayam"] },
  { name: "Mie Yamin", category: ["Mie"] },
  { name: "Mie Goreng", category: ["Mie"] },
  { name: "Mie Aceh", category: ["Mie"] },
  { name: "Mie Tek-Tek", category: ["Mie"] },
  { name: "Mie Godog", category: ["Mie"] },
  { name: "Mie Kari", category: ["Mie"] },
  { name: "Cwi Mie", category: ["Mie"] },
  { name: "Mie Laksa", category: ["Mie"] },
  { name: "Udon", category: ["Mie"] },
  { name: "Pad Thai", category: ["Mie"] },
  { name: "Ramyeon", category: ["Mie"] },
  { name: "Jajangmyeon", category: ["Mie"] },
];

export const foodCategories = [
  { name: "Aneka Nasi", value: "anekaNasi" },
  { name: "Makanan Berkuah", value: "makananBerkuah" },
  { name: "Mie", value: "mie" },
  { name: "Seafood", value: "seafood" },
  { name: "Daging Ayam", value: "dagingAyam" },
  { name: "Daging Sapi", value: "dagingSapi" },
  { name: "Daging Kambing", value: "dagingKambing" },
];
