export const foods = [
  { name: "Nasi Padang", category: ["Aneka Nasi"] },
  { name: "Nasi Campur", category: ["Aneka Nasi"] },
  { name: "Nasi Goreng", category: ["Aneka Nasi"] },
  { name: "Nasi Uduk", category: ["Aneka Nasi"] },
  { name: "Nasi Lemak", category: ["Aneka Nasi"] },
  { name: "Nasi Bakar", category: ["Aneka Nasi"] },
  { name: "Nasi Gila", category: ["Aneka Nasi"] },
  { name: "Nasi Liwet", category: ["Aneka Nasi"] },
  { name: "Nasi Lalapan", category: ["Aneka Nasi"] },
  { name: "Nasi Kuning", category: ["Aneka Nasi"] },
  { name: "Nasi Kebuli", category: ["Aneka Nasi"] },
  { name: "Nasi Briyani", category: ["Aneka Nasi"] },
  { name: "Nasi Hainan", category: ["Aneka Nasi"] },
  { name: "Bakso", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Rawon", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Sop Ayam", category: ["Makanan Berkuah", "Daging Ayam"] },
  { name: "Sop Iga", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Sop Buntut", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Konro", category: ["Makanan Berkuah", "Daging Sapi"] },
  { name: "Soto Lamongan", category: ["Makanan Berkuah"] },
  { name: "Soto Betawi", category: ["Makanan Berkuah"] },
  { name: "Soto Banjar", category: ["Makanan Berkuah"] },
  { name: "Coto Makassar", category: ["Makanan Berkuah", "Daging Sapi"] },
  {
    name: "Gulai",
    category: ["Makanan Berkuah", "Daging Sapi", "Daging Kambing"],
  },
  {
    name: "Tongseng",
    category: ["Makanan Berkuah", "Daging Sapi", "Daging Kambing"],
  },
  { name: "Ramen", category: ["Makanan Berkuah", "Jepang"] },
  { name: "Pho", category: ["Makanan Berkuah"] },
  { name: "Tom Yum", category: ["Makanan Berkuah", "Thailand"] },
  { name: "Bakmie", category: ["Mie"] },
  { name: "Mie Ayam", category: ["Mie", "Daging Ayam"] },
  { name: "Mie Yamin", category: ["Mie"] },
  { name: "Mie Goreng", category: ["Mie"] },
  { name: "Mie Aceh", category: ["Mie"] },
  { name: "Mie Tek-Tek", category: ["Mie"] },
  { name: "Mie Godog", category: ["Mie"] },
  { name: "Mie Kari", category: ["Mie"] },
  { name: "Cwi Mie", category: ["Mie"] },
  { name: "Mie Laksa", category: ["Mie"] },
  { name: "Udon", category: ["Mie", "Jepang"] },
  { name: "Pad Thai", category: ["Mie", "Thailand"] },
  { name: "Ramyeon", category: ["Mie", "Korea"] },
  { name: "Jajangmyeon", category: ["Mie", "Korea"] },
  { name: "Sushi", category: ["Seafood", "Jepang"] },
  { name: "Sashimi", category: ["Seafood", "Jepang"] },
  { name: "Ikan Bakar", category: ["Seafood"] },
  { name: "Ikan Goreng", category: ["Seafood"] },
  { name: "Sop Ikan", category: ["Seafood", "Makanan Berkuah"] },
  { name: "Udang Goreng", category: ["Seafood"] },
  { name: "Udang Bakar", category: ["Seafood"] },
  { name: "Udang Asam Manis", category: ["Seafood"] },
  { name: "Udang Mentega", category: ["Seafood"] },
  { name: "Cumi Goreng Tepung", category: ["Seafood"] },
  { name: "Cumi Hitam", category: ["Seafood"] },
  { name: "Kerang Saus Padang", category: ["Seafood"] },
  { name: "Pepes Ikan", category: ["Seafood"] },
  { name: "Sate Ayam", category: ["Daging Ayam"] },
  { name: "Ayam Goreng", category: ["Daging Ayam"] },
  { name: "Ayam Bakar", category: ["Daging Ayam"] },
  { name: "Ayam Panggang", category: ["Daging Ayam"] },
  { name: "Ayam Geprek", category: ["Daging Ayam"] },
  { name: "Ayam Kremes", category: ["Daging Ayam"] },
  { name: "Ayam Penyet", category: ["Daging Ayam"] },
  { name: "Ayam Rica-Rica", category: ["Daging Ayam"] },
  { name: "Ayam Betutu", category: ["Daging Ayam"] },
  { name: "Chicken Katsu", category: ["Daging Ayam"] },
  { name: "Chicken Wings", category: ["Daging Ayam"] },
  { name: "Bebek Goreng", category: ["Daging Bebek"] },
  { name: "Bebek Bakar", category: ["Daging Bebek"] },
  { name: "Bebek Kremes", category: ["Daging Bebek"] },
  { name: "Bebek Hitam Madura", category: ["Daging Bebek"] },
  { name: "Sei Sapi", category: ["Daging Sapi"] },
  { name: "Soto Daging", category: ["Daging Sapi", "Makanan Berkuah"] },
  { name: "Tengkleng", category: ["Daging Sapi"] },
  { name: "Sate Padang", category: ["Daging Sapi"] },
  { name: "Steak", category: ["Daging Sapi"] },
  { name: "Beef Bulgogi", category: ["Daging Sapi", "Korea"] },
  { name: "Beef Teriyaki", category: ["Daging Sapi", "Jepang"] },
  { name: "Sate Kambing", category: ["Daging Kambing"] },
  { name: "Burger", category: ["Fast Food"] },
  { name: "Pizza", category: ["Fast Food"] },
  { name: "Fried Chicken", category: ["Fast Food", "Daging Ayam"] },
  { name: "Sandwich", category: ["Fast Food"] },
  { name: "Taco", category: ["Fast Food"] },
  { name: "Bento", category: ["Fast Food", "Aneka Nasi"] },
];

export const foodCategories = [
  ...new Set(foods.flatMap((food) => food.category)),
];

// export const foodCategories = [
//   "Aneka Nasi",
//   "Makanan Berkuah",
//   "Mie",
//   "Seafood",
//   "Daging Ayam",
//   "Daging Sapi",
//   "Daging Kambing",
// ];
